export const data =[
    {
        id:1,
        title1:"Nimona",
        title2:"The Magic of the Lost temple",
        title3:"HeartStopper",
        title4:"Hark! A Vagrant",
        
        details4:"MRP-$300",
        details3:"MRP-$125",

        details2:"MRP-$225",
        image2:"https://tse3.mm.bing.net/th?id=OIP.w7Rnnuv2njcbCH30XxUg_QHaLY&pid=Api&P=0",
        image3:"https://tse1.mm.bing.net/th?id=OIP.Y8iWwb0rrZPcxA3qtwbuPAHaLT&pid=Api&P=0",
        image4:"https://tse1.mm.bing.net/th?id=OIP.Y6s45I0M-nS673zRk7EdKwAAAA&pid=Api&P=0",
        image1:"https://tse4.mm.bing.net/th?id=OIP.jY-rSbxDp86tESAAbitGKgHaLG&pid=Api&P=0",
        desc1:"The graphic novel debut from rising star ND Stevenson, based on his beloved and critically acclaimed web comic, which Slate awarded its Cartoonist Studio Prize, calling it a deadpan epic.Nemeses! Dragons! Science! Symbolism! All these and more await in this brilliantly subversive, sharply irreverent epic from Noelle Stevenson. Featuring an exclusive epilogue not seen in the web comic, along with bonus conceptual sketches and revised pages throughout, this gorgeous full-color graphic novel is perfect for the legions of fans of the web comic and is sure to win Noelle many new ones.Nimona is an impulsive young shapeshifter with a knack for villainy. Lord Ballister Blackheart is a villain with a vendetta. As sidekick and supervillain, Nimona and Lord Blackheart are about to wreak some serious havoc.",
        desc2:"City girl Nooni is surprised at the pace of life in her grandparents’ village in Karnataka. But she quickly gets used to the gentle routine there and involves herself in a flurry of activities, including papad making, organizing picnics and learning to ride a cycle, with her new-found friends. Things get exciting when Nooni stumbles upon an ancient fabled stepwell right in the middle of a forest. Join the intrepid Nooni on an adventure of a lifetime in this much-awaited book by Sudha Murty that is heart-warming, charming and absolutely unputdownable",
        desc3:"Originally a comic on Tumblr and Tapas, Heartstopper has amassed an enormous online fanbase with over 52.1 million views to date. Alice Oseman crowd-funded a limited print-run edition, meeting her funding goal in less than two hours. Hachette Children’s Group published Heartstopper Volume One more widely in Spring 2019, followed by Volume Two in July of the same year. Since then, Hachette Children’s Group have published a further two volumes and a colouring book",
        desc4:"Praised for their expression, intelligence and comic timing, her cartoons are best known for their wonderfully light touch on historical and literary topics. The jokes are a knowing look at history through a very modern perspective, written for every reader, and are a crusade against anyone with the idea that history is boring. It's pretty hard to argue with that when you're laughing your head off at a comic about Thucydides. They also cover whatever's on her mind that week - be it the perils of city living or the pop-cultural infiltration of Sex and the City, featuring an array of characters, from a mischievous pony, to reinvented superheroes, to a surly teen duo who could be the anti-Hardy-Boys.",
        img1:"nomino.jpg",
        img2:"tmlt.jpeg",
        img3:"heartstopper.jpeg",
        img4:"vagrant.jpeg",
        details1:"MRP-$235",
        
       
    },
    {
        id:2,
        title1:"Maus",
        title2:"IKIGAI",
        title3:"Falling For a Korean",
        title4:"Megahex",
        
        details4:"MRP-$130",
        details3:"MRP-$200",

        details2:"MRP-$450",
        image2:"https://tse3.mm.bing.net/th?id=OIP.U1cUGTfX8srC2SYviWRvewHaLD&pid=Api&P=0",
        image3:"https://tse1.mm.bing.net/th?id=OIP.5Q3LX7Ld-pQKsadGQJGLpQHaLH&pid=Api&P=0",
        image4:"https://tse2.mm.bing.net/th?id=OIP.66_atzg8PXi65LfdcnlkBgHaKy&pid=Api&P=0",
        image1:"https://tse4.mm.bing.net/th?id=OIP.Y1ug6Gz4TCW_1o_7i2kUeQDREs&pid=Api&P=0",
        desc1:"Maus,[a] often published with the subtitle A Survivor's Tale, is a graphic novel by American cartoonist Art Spiegelman, serialized from 1980 to 1991. It depicts Spiegelman interviewing his father about his experiences as a Polish Jew and Holocaust survivor. The work employs postmodern techniques, and represents Jews as mice and other Germans and Poles as cats and pigs. Critics have classified Maus as memoir, biography, history, fiction, autobiography, or a mix of genres. In 1992 it became the first graphic novel to win a Pulitzer Prize.",
        desc2:"Everyone has an ikigai—a reason for living. And according to the residents of the Japanese village with the world’s longest-living people, finding it is the key to a happier and longer life. Having a strong sense of ikigai—where what you love, what you’re good at, what you can get paid for, and what the world needs all overlap—means that each day is infused with meaning. It’s the reason we get up in the morning. It’s also the reason many Japanese never really retire (in fact there’s no word in Japanese that means retire in the sense it does in English):",
        desc3:"Falling for a Korean ..is a Story of love between an Indian girl and a Korean Guy. Does running away from your situations make you get something you never expected?? Here the Female Protagonist Maya,runs out of the country to escape her hardship in her career and her heart break.",
        desc4:"Packaged like a DVD box set with an end-sheet inspired by John Everett Millais’ painting of Ophelia, Simon Hanselmann’s Megahex — a collection of his popular episodic comic — is much more ambitious than its stoner characters might initially suggest. The small cast features Megg (a witch), Mogg (a cat/Megg’s lover) and Owl (a humanoid owl); the trio share a house where they spend most of their time smoking weed, watching TV and going on misadventures that start out comedic and slowly turn tragic. It’s not just Megg’s depressive episodes, which are impressively bleak on their own,",
        img1:"maus.jpeg",
        img2:"ikigai.jpeg",
        img3:"ffcorean.jpeg",
        img4:"megahex.jpeg",
        img:"th.jpeg",
        details1:"MRP-$75",
       
    },
    {
        id:3,
        title1:"A Contract with God",
        title2:"The Girl Who Drank The Moon",
        title3:"All I Ever Want Is You",
        title4:"Cryptid Club",
        
        details4:"MRP-$50",
        details3:"MRP-$100",

        details2:"MRP-$45",
        image2:"https://tse4.mm.bing.net/th?id=OIP.qMpDAf_p5FKfdcCaDCHO_QHaLE&pid=Api&P=0",
        image3:"https://tse1.mm.bing.net/th?id=OIP.ecweD06DEMcrOKgfY8czMgHaL7&pid=Api&P=0",
        image4:"https://tse1.mm.bing.net/th?id=OIP.-keJFp7igeJk91D_JXYqrAHaJO&pid=Api&P=0",
        image1:"https://tse2.mm.bing.net/th?id=OIP.lUhzilzTYEyuybrkRkLq9gHaJ4&pid=Api&P=0",
        desc1:"Four stand-alone stories make up the book: in A Contract with God a religious man gives up his faith after the death of his young adopted daughter; in The Street Singer a has-been diva tries to seduce a poor, young street singer, who tries to take advantage of her in turn; a bullying racist is led to suicide after false accusations of pedophilia in The Super; and Cookalein intertwines the stories of several characters vacationing in the Catskill Mountains. The stories are thematically linked with motifs of frustration, disillusionment, violence, and issues of ethnic identity",
        desc2:"The Girl Who Drank the Moon is a 2016 children's book by Kelly Barnhill. The book tells how Luna, after being raised by a witch named Xan, must figure out how to handle the magical powers she was accidentally given. She must control her powers before it's too late. The book won the 2017 Newbery Medal.[1]Every year the townspeople abandon the youngest baby in the forest, as a gift for the bad witch they fear. The witch Xan however, whom the townspeople believe to be the source of all evil, takes the little babies and gives them to another town, where the people raise these children like their own. While doing the same to another baby girl, Xan accidentally feeds the little creature moonlight instead of the starlight she actually feeds them.",
        desc3:"Raj and Alisha meet at a family party and fall for each other, later they realise they love each other, but until then, they have drifted apart due to some family drama. ‘All I Ever Want Is You’ is the story of finding love, finding passion, and separation. This is a story that defines love, a journey that leads you to love your loved ones and yourself.",
        desc4:"Cryptid Club is a creative comics collection that combines mythical legends, pop culture and dark humour. It's a refreshing deviation from the Sarah's Scribbles series, but equally enjoyable and relatable nonetheless as the book depicts situations that all introverts will be familiar with.",
        img1:"a contract with god.jpeg",
        img2:"the girl who drank the moon.jpeg",
        img3:"akk i ever.jpeg",
        img4:"club.jpeg",
        img:"th.jpeg",
        details1:"MRP-$55",
    },
    {
        id:4,
        title1:"Watchmen",
        title2:"In Cold Blood",
        title3:"True Beauty",
        title4:"Dog Man",
        
        details4:"MRP-$125",
        details3:"MRP-$30",

        details2:"MRP-$45",
        image2:"https://tse3.mm.bing.net/th?id=OIP.NRckdbqPrEXDgzMRZK9S2gHaKL&pid=Api&P=0",
        image3:"https://tse4.mm.bing.net/th?id=OIP.1sWyFwYwbFEWVhGUFWrg-wHaHa&pid=Api&P=0",
        image4:"https://tse3.mm.bing.net/th?id=OIP.9P64SwwkCiD3Nu4hAbQkIwHaKv&pid=Api&P=0",
        image1:"https://tse2.mm.bing.net/th?id=OIP.-uBI2k_7x1BITMI91qHkvgHaJc&pid=Api&P=0",
        desc1:"Moore used the story as a means to reflect contemporary anxieties, to deconstruct and satirize the superhero concept and political commentary. Watchmen depicts an alternate history in which superheroes emerged in the 1940s and 1960s and their presence changed history so that the United States won the Vietnam War and the Watergate scandal was never exposed. In 1985, the country is edging toward World War III with the Soviet Union, freelance costumed vigilantes have been outlawed and most former superheroes are in retirement or working for the government",
        desc2:"Capote learned of the quadruple murder before the killers were captured, and he traveled to Kansas to write about the crime. He was accompanied by his childhood friend and fellow author Harper Lee, and they interviewed residents and investigators assigned to the case and took thousands of pages of notes. Killers Richard Hickock and Perry Smith were arrested six weeks after the murders and later executed by the state of Kansas. Capote ultimately spent six years working on the book.",
        desc3:"Jugyeong Lim has been treated unfairly by her family and bullied by her enemies due to being perceived as ugly. She learns how to use makeup by binge-watching Youtube tutorials. As she slowly masters the art of makeovers, her dramatic transformation leads to her overwhelming popularity and fame.",
        desc4:"When Greg the police dog and his cop companion are injured on the job, a life-saving surgery changes the course of history, and Dog Man is born. With the head of a dog and the body of a human, this heroic hound has a real nose for justice. But can he resist the call of the wild to answer the call of duty?",
        img1:"watchmen.jpeg",
        img2:"in cold blood.jpeg",
        img3:"truebeauty.jpeg",
        img4:"dogman.jpeg",
        img:"th.jpeg",
        details1:"MRP-$20",
    },
    {
        id:5,
        title1:"Marvels",
        title2:"Guns,Germs and Steel",
        title3:"Seasons of Blossom",
        title4:"Reunion",
        
        details4:"MRP-$125",
        details3:"MRP-$55",

        details2:"MRP-$200",
        image2:"https://tse2.mm.bing.net/th?id=OIP.rSLHOZ9RUxxlG-ApnBAAgwAAAA&pid=Api&P=0",
        image3:"https://tse1.mm.bing.net/th?id=OIP.-R7_XG43hBYBRYlu8Z-RngAAAA&pid=Api&P=0",
        image4:"https://tse2.mm.bing.net/th?id=OIP.ZP-1vl4A4QkeG3_XS5fd7QAAAA&pid=Api&P=0",
        image1:"https://tse3.mm.bing.net/th?id=OIP.iInXGXCAtREGjjGIB9l3RwHaLY&pid=Api&P=0",
        desc1:"Experience the Marvel Universe through the eyes of the man on the street: photographer and family man Phil Sheldon. Follow years of history through the writing of Kurt Busiek and first major painted work by Alex Ross in one of Marvel's most beloved series of all-time.",
        desc2:"The book attempts to explain why Eurasian and North African civilizations have survived and conquered others, while arguing against the idea that Eurasian hegemony is due to any form of Eurasian intellectual, moral, or inherent genetic superiority. Diamond argues that the gaps in power and technology between human societies originate primarily in environmental differences",
        desc3:"Seasons of Blossom tells the story of love and friendship of 18-year-old youths at Seoyeon High School. The drama depicts the butterfly effect that occurs from a tragic incident six years ago as it begins to affect the current teens living in the present",
        desc4:"After moving away for a decade, Rhea returns to the bustling city on her quest for independence. Things are looking bleak, until she bumps into a familiar face - one she didn't think she would ever see again. Feelings rekindle as secrets begin to unfold, Rhea soon realizes her childhood friend may not be who she believes him to be, and thus her most cherished relationship is put to the test.",
        img1:"marvels.jpeg",
        img2:"ggs.jpeg",
        img3:"blossom.jpeg",
        img4:"reunion.jpeg",
        img:"th.jpeg",
        details1:"MRP-$120",
        name:"garnet",
        d:"mrp:100"
       
    },
    {
        id:6,
        title1:"Marvel Super Heroes Secret Wars",
        title2:"We Dream of Space",
        title3:"Your Name",
        title4:"Phoebe and Her Unicorn",
        
        details4:"MRP-$125",
        details3:"MRP-$45",

        details2:"MRP-$150",
        image2:"https://tse3.mm.bing.net/th?id=OIP.MvTr1aJxbKn8b5uTJTiYRAHaD4&pid=Api&P=0",
        image3:"https://tse1.mm.bing.net/th?id=OIP.bRHP1MpNY9ceXoyTrHf20AHaLH&pid=Api&P=0",
        image4:"https://tse4.mm.bing.net/th?id=OIP.eQSN55gkv7kxwbB3Fm1IHAHaLU&pid=Api&P=0",
        image1:"https://tse1.mm.bing.net/th?id=OIP.1exF-mpbMQQkI3S4lQeZxQHaLS&pid=Api&P=0",
        desc1:"The series was conceived by Marvel Comics' editor-in-chief Jim Shooter. The series was announced as Cosmic Champions in the eleventh issue of the Marvel Age news magazine, cover dated February 1984. The following issue had a cover story on the series, which had been renamed Secret Wars.Kenner had licensed the DC Heroes, and Mattel had He-Man, but wanted to hedge in case superheroes became the next big fad. They were interested in Marvel's characters, but only if we staged a publishing event that would get a lot of attention, and they could build a theme around",
        desc2:"Newbery Medalist and New York Times–bestselling author Erin Entrada Kelly transports readers to 1986 and introduces them to the unforgettable Cash, Fitch, and Bird Nelson Thomas in this pitch-perfect middle grade novel about family, friendship, science, and exploration. This acclaimed Newbery Honor Book is a great choice for readers of Kate DiCamillo, Rita Williams-Garcia, and Rebecca Stead.",
        desc3:"A story of two people determined to hold on to one another. Mitsuha, a high school girl from a town deep in the mountains, dreams of an unfamiliar life in Tokyo. Taki, a high school boy from Tokyo, dreams that he is a girl living in the mountains. As the two begin swapping lives, a miraculous story is set in motion.",
        desc4:"Phoebe and Her Unicorn is a daily children's comic strip by American cartoonist Dana Simpson. Originally called Heavenly Nostrils, the strip debuted as a webcomic on April 22, 2012, in Universal Uclick's GoComics website.[1] It was later launched in more than 100 newspapers on March 30, 2015, under the current name.The strip begins when 9-year-old Phoebe Howell skips a rock across a pond and accidentally hits a unicorn in the face. Freed from the trap of gazing at her own reflection in the pond, a unicorn named Marigold Heavenly Nostrils gives Phoebe one wish, which she decides to use by making the unicorn her best friend",
        img1:"marvels secret wars.jpeg",
        img2:"we dream of space.jpeg",
        img3:"name.jpeg",
        img4:"pheobe.jpeg",
        img:"th.jpeg",
        details1:"MRP-$80",
        name:"garnet",
        d:"mrp:100"
       
    },
    {
        id:7,
        title1:"Extremis",
        title2:"You Only Live once",
        title3:"Bloom",
        title4:"Everything is Flammable",
        
        details4:"MRP-$100",
        details3:"MRP-$250",

        details2:"MRP-$55",
        image2:"https://tse4.mm.bing.net/th?id=OIP.8hOk558hyNbswfEGyD0i7AHaHa&pid=Api&P=0",
        image3:"https://tse3.mm.bing.net/th?id=OIP.3xZzvjygazp1tgQ5-flcgwHaKf&pid=Api&P=0",
        image4:"https://tse3.mm.bing.net/th?id=OIP.w0FmWZb4C0PE7rB8eonO8QAAAA&pid=Api&P=0",
        image1:"https://tse2.mm.bing.net/th?id=OIP.IcfRf5Jb9ui0f9oJPU8FeQHaLK&pid=Api&P=0",
        desc1:"Extremis received mostly positive reviews, and it is often listed as one of the best Iron Man stories. Elements of Extremis were adapted for the 2008 film Iron Man,[6] and the Iron Man: Armored Adventures episode Extremis,and the storyline serves as the primary source material for the 2013 film Iron Man 3.",
        desc2:"Twenty years later, three people are looking for you.One is dying to meet you again.The other wishes you had never met them.The third wishes they could have met you at least once.You are one person. Aren't you? But you are not the same person to each of them.",
        desc3:"Now that high school is over, Ari is dying to move to the big city with his ultra-hip band—if he can just persuade his dad to let him quit his job at their struggling family bakery. Though he loved working there as a kid, Ari cannot fathom a life wasting away over rising dough and hot ovens. But while interviewing candidates for his replacement, Ari meets Hector, an easygoing guy who loves baking as much as Ari wants to escape it. As they become closer over batches of bread, love is ready to bloom . . . that is, if Ari doesn’t ruin everything.",
        desc4:"In Gabrielle Bell’s much anticipated graphic memoir, EVERYTHING IS FLAMMABLE, she returns from New York to her childhood town in rural Northern California after her mother’s home is destroyed by a fire. Acknowledging her issues with anxiety, financial hardships, memories of a semi-feral childhood, and a tenuous relationship with her mother, Bell helps her mother put together a new home on top of the ashes. A powerful, sometimes uncomfortable, examination of a mother-daughter relationship and one’s connection to place and sense of self",
        img1:"extremis.jpeg",
        img2:"you only live once.jpeg",
        img3:"bloom.jpeg",
        img4:"flame.jpeg",
        img:"th.jpeg",
        details1:"MRP-$175",
    },
    {
        id:8,
        title1:"From Hell",
        title2:"Tintin in Tibet",
        title3:"Twisted Romance",
        title4:"Out From Boneville",
        
        details4:"MRP-$25",
        details3:"MRP-$75",

        details2:"MRP-$65",
        image2:"https://tse1.mm.bing.net/th?id=OIP.JnBgYcjb4DptNYzdgtTtAAHaJ4&pid=Api&P=0",
        image3:"https://tse1.mm.bing.net/th?id=OIP.zwXYtQBFtpkNesbCQ7WcBwHaLQ&pid=Api&P=0",
        image4:"https://tse2.mm.bing.net/th?id=OIP.SVCUZRV6DPz56dS7M7cdhgHaLH&pid=Api&P=0",
        image1:"https://tse2.mm.bing.net/th?id=OIP.6Es14FLOsYFR7pqrIeJ6FwHaJ5&pid=Api&P=0",
        desc1:"Set during the Whitechapel murders of the late Victorian era, the novel speculates upon the identity and motives of Jack the Ripper. The novel depicts several true events surrounding the murders, although portions have been fictionalised, particularly the identity of the killer and the precise nature and circumstances of the murders.",
        desc2:"A passenger plane travelling to Europe, crashes into the Himalayas. It turns out that Tintin's young Chinese friend Chang was on board the aircraft. Tintin in Tibet (1960) is a story of pure friendship, without any of the usual villains: a tale of Tintin's desperate search to find his friend.",
        desc3:"Four stories of love and lust from comics’ coolest artists and writer ALEX de CAMPI! First, a demon prowls the 1978 New York disco scene in “OLD FLAMES,” drawn by KATIE SKELLY. Then, a curvy photographer’s assistant falls in love with someone way out of her league in “TWINKLE & THE STAR,” with art from ALEJANDRA GUTIÉRREZ. A spacefleet captain captures a most infuriating pirate in “INVINCIBLE HEART,” drawn by CARLA SPEED McNEIL. And a princess runs away with a dragon in “TREASURED,” featuring art by TRUNGLES. Plus steamy prose romance stories from awesome folks like MAGEN CUBED and VITA AYALA",
        desc4:"Out From Boneville is the first story-arc in the Bone series. It collects the first six issues of Jeff Smith's self-published Bone comics. It marks the beginning of part one (of three) of the Bone series, titled Vernal Equinox. The book was first published by Cartoon Books in its original black-and-white version in 1995; excerpts were printed in Disney Adventures over the course of 1994–1998. Paperback and hardback colored editions were published in 2005 by Scholastic",
        img1:"from hell.jpeg",
        img2:"tintin in tibet.jpeg",
        img3:"twisted.jpeg",
        img4:"boneville.jpeg",
        img:"th.jpeg",
        details1:"MRP-$55",
    },
    {
        id:9,
        title1:"Kingdom Come",
        title2:"Suppandi",
        title3:"Fresh Romance",
        title4:"The Great Cow Race",
        
        details4:"MRP-$90",
        details3:"MRP-$125",

        details2:"MRP-$300",
        image2:"https://tse2.mm.bing.net/th?id=OIP.OSqf_qeo-UaqEP8gJZ5rNAAAAA&pid=Api&P=0",
        image3:"https://tse4.mm.bing.net/th?id=OIP.P0i-iFkUa5L0fhbwKPzpPwHaLH&pid=Api&P=0",
        image4:"https://tse4.mm.bing.net/th?id=OIP.-mGrOMTFKnsM1zcmcJfYMwHaLU&pid=Api&P=0",
        image1:"https://tse2.mm.bing.net/th?id=OIP.9FXPAOYkNUNRmImAvLOSzgHaLS&pid=Api&P=0",
        desc1:"The story is set in an alternate future of the DC Universe. The new generation of heroes have lost their moral compass, becoming as reckless and violent as the villains they fight. The previous regime of heroes—the Justice League—returns under dire circumstances, which sets up a battle of the old guard against these uncompromising protectors in a conflict that will define what heroism truly is and determine the future of the planet.",
        desc2:"Suppandi made his debut in Tinkle No. 27 in January 1983.[1] Unlike other Tinkle characters, he was not originally conceptualized by the creators of the magazine. He was born out of 3 narrative stories sent by P. Varadarajan from Trichy. The concept was rendered into a comic format in Tinkle studios, with illustrations by one of the famous yesteryear artists, Ram Waeerkar. Suppandi is also shown as an ignoramus but a faithful servant to his masters most of the time. His stupidity or his virtue of being an ignoramus has cost him many a job. Often Suppandi is shown living in big towns and cities",
        desc3:"The critically-acclaimed anthology FRESH ROMANCE is finally available in print! Have you been wondering what the fuss is all about? FRESH ROMANCE is an exciting collection of romance comics from some of comics most talented creators, including Kate Leth, Arielle Jovellanos, Sarah Vaughn, Sarah Winifred Searle, Sarah Kuhn, Marguerite Bennett, and Trungles. From unhappy historical marriages to covert teenage romances, there's something for everyone in FRESH ROMANCE",
        desc4:"This volume focuses on Gran'ma Ben's annual race against the town's cows, and Phoney and Smiley Bone's attempts to fix the race. It also delves into the deepening mystery of Thorn's past, and the brooding unrest between the valley folk and the Rat Creature tribe, between whom there has been an uneasy treaty.",
        img1:"kingdom come.jpeg",
        img2:"suppandi.jpeg",
        img3:"romance.jpeg",
        img4:"cow.jpeg",
        img:"th.jpeg",
        details1:"MRP-$200",
    },
    {
        id:10,
        title1:"BTTM FDRS",
        title2:"Spy Family",
        title3:"AFTER:The Graphic Novel",
        title4:"My Dirty Dumb Eyes",
        
        details4:"MRP-$200",
        details3:"MRP-$250",

        details2:"MRP-$100",
        image2:"https://tse1.mm.bing.net/th?id=OIP.YOo8cnoHo8CRI29Q-yA2cQHaLH&pid=Api&P=0",
        image3:"https://tse1.mm.bing.net/th?id=OIP.IT1mgBH94cGTwqnWKY3j0gAAAA&pid=Api&P=0",
        image4:"https://tse2.mm.bing.net/th?id=OIP.zkaTCx9hXQEUv28i91mwPgHaJ7&pid=Api&P=0",
        image1:"https://tse1.mm.bing.net/th?id=OIP.pkuA4sBirlFcBCWzJXH6kQAAAA&pid=Api&P=0",
        desc1:"Once a thriving working class neighborhood on Chicago’s south side, the Bottomyards is now the definition of urban blight. When an aspiring fashion designer named Darla and her image-obsessed friend, Cynthia, descend upon the neighborhood in search of cheap rent, they soon discover something far more seductive and sinister lurking behind the walls of their new home. Like a cross between Jordan Peele’s Get Out and John Carpenter’s The Thing, Daniels and Passmore’s BTTM FDRS (pronounced “bottomfeeders”) offers a vision of horror that is gross and gory in all the right ways.",
        desc2:"A spy on an undercover mission gets married and adopts a child as part of his cover. His wife and daughter have secrets of their own, and all three must strive to keep together. A spy on an undercover mission gets married and adopts a child as part of his cover.",
        desc3:"As good girl Tessa Young embarks on her first year of college at Washington Central University, she has direction, ambition and a new circle of friends who are always trying to push her beyond her comfort zone. Chief among them is fellow student, campus bad boy – and son of the University’s Chancellor– Hardin Scott, who has simultaneously enraged and seduced her. Tessa can hardly abide Hardin’s antics and ex-girlfriends yet, despite their differences, Tessa and Hardin are undeniably, passionately drawn to one other, and willing to risk a bumpy ride for a romance that will consume and change them both",
        desc4:"On a back cover blurb, Patton Oswalt writes that My Dirty Dumb Eyes is a [Lisa] Hanawalt assault. I'd argue that this book isn't quite the Full Hanawalt, not compared with her astonishing debut minicomics Stay Away From Other People and (especially) I Want You. Not since Ivan Brunetti published Schizo #1 had I seen such a buzz around a new cartoonist, especially a humorist. The hype was well-deserved largely because of Hanawalt's titular the dirty dumb eyes.",
        img1:"bttm.jpeg",
        img2:"spy family.jpeg",
        img3:"novel.jpeg",
        img4:"eyes.jpeg",
        img:"th.jpeg",
        details1:"MRP-$150",
    },
   
]
       